@echo off
REM Rebuild everything after you change content, then reindex the agent.
cd /d "%~dp0"
echo [1/5] Syncing content...
python sync_docs.py
echo [2/5] Building interview practice questions...
python build_practice_questions.py
echo [3/5] Building site...
python -m mkdocs build --clean
echo [4/5] Copying module files...
python finalize_site.py
echo [5/5] Reindexing agent...
python agent\ask.py --reindex
echo.
echo Done. Run start.bat to view at http://localhost:8080
pause
